workflows:
  android-build:
    name: Build Android APK
    environment:
      node: 18.16.0
    scripts:
      - npm install
      - npx cap sync android
      - npx cap copy android
      - cd android
      - chmod +x gradlew
      - ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
